source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'XBike' do
  use_frameworks!
    pod 'GoogleMaps', '7.0.0'

  target 'XBikeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XBikeUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end


